### ISSUE TITLE
Doesn't work on Debian?

### ISSUE THREAD

**Issue by emilfihlman** [gto76/comp-m2#5]
> emil@emil:~$ uname -a
> Linux emil 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux
> emil@emil:~$ sudo apt-get install build-essential
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> build-essential is already the newest version.
> The following packages were automatically installed and are no longer required:
>  dbconfig-common javascript-common libaio1 libapparmor1 libdbi-perl libjs-jquery libjs-sphinxdoc libjs-underscore libmcrypt4 libonig2 libqdbm14 libterm-readkey-perl
> Use 'apt-get autoremove' to remove them.
> 0 upgraded, 0 newly installed, 0 to remove and 50 not upgraded.
> emil@emil:~$ git clone https://github.com/gto76/comp-m2.git
> Cloning into 'comp-m2'...
> remote: Counting objects: 2451, done.
> remote: Total 2451 (delta 0), reused 0 (delta 0), pack-reused 2451
> Receiving objects: 100% (2451/2451), 766.90 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (1767/1767), done.
> Checking connectivity... done.
> emil@emil:~$ cd comp-m2/
> emil@emil:~/comp-m2$ ./run
> Compiling... (may take some time)
> mkdir -p obj
> g++ -c -std=c++11 -Wall -g -O0 -o obj/printer.o src/printer.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/printer.o' src/printer.cpp > obj/printer.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/cursor.o src/cursor.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/cursor.o' src/cursor.cpp > obj/cursor.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/specific_instruction.o src/specific_instruction.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/specific_instruction.o' src/specific_instruction.cpp > >obj/specific_instruction.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/pipe_input.o src/pipe_input.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/pipe_input.o' src/pipe_input.cpp > obj/pipe_input.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/view.o src/view.cpp
> emil@emil:~/comp-m2$ ./comp
> -bash: ./comp: No such file or directory
> emil@emil:~/comp-m2$

**Comment by gto76** [comment]
Can you run `make clean` and then `make`. It will print the compile errors.

**Comment by emilfihlman** [comment]
> emil@emil:~$ cd comp-m2/
> emil@emil:~/comp-m2$ make clean
> rm -f obj/\* comp
> emil@emil:~/comp-m2$ make
> g++ -c -std=c++11 -Wall -g -O0 -o obj/printer.o src/printer.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/printer.o' src/printer.cpp > obj/printe                                                                                               r.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/cursor.o src/cursor.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/cursor.o' src/cursor.cpp > obj/cursor.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/specific_instruction.o src/specific_instru                                                                                               ction.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/specific_instruction.o' src/specific_instruction.cpp > obj/specific_                                                                  instruction.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/pipe_input.o src/pipe_input.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/pipe_input.o' src/pipe_input.cpp > obj/pipe_input.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/view.o src/view.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/view.o' src/view.cpp > obj/view.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/output.o src/output.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/output.o' src/output.cpp > obj/output.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/instruction.o src/instruction.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/instruction.o' src/instruction.cpp > obj/instruction.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/renderer.o src/renderer.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/renderer.o' src/renderer.cpp > obj/renderer.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/noninteractive_mode.o src/noninteractive_mode.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/noninteractive_mode.o' src/noninteractive_mode.cpp > obj/noninteractive_mode.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/interactive_mode.o src/interactive_mode.cpp
> virtual memory exhausted: Cannot allocate memory
> makefile:31: recipe for target 'obj/interactive_mode.o' failed
> make: **\* [obj/interactive_mode.o] Error 1
> emil@emil:~/comp-m2$

**Comment by emilfihlman** [comment]
Ran it again, this time with different results o.0

> emil@emil:~$ cd comp-m2/
> emil@emil:~/comp-m2$ make clean
> rm -f obj/\* comp
> emil@emil:~/comp-m2$ make
> g++ -c -std=c++11 -Wall -g -O0 -o obj/printer.o src/printer.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/printer.o' src/printer.cpp > obj/printe                                                                                                                  r.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/cursor.o src/cursor.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/cursor.o' src/cursor.cpp > obj/cursor.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/specific_instruction.o src/specific_instru                                                                                                                  ction.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/specific_instruction.o' src/specific_in                                                                                                                  struction.cpp > obj/specific_instruction.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/pipe_input.o src/pipe_input.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/pipe_input.o' src/pipe_input.cpp > obj/                                                                                                                  pipe_input.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/view.o src/view.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/view.o' src/view.cpp > obj/view.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/output.o src/output.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/output.o' src/output.cpp > obj/output.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/instruction.o src/instruction.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/instruction.o' src/instruction.cpp > ob                                                                                                                  j/instruction.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/renderer.o src/renderer.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/renderer.o' src/renderer.cpp > obj/rend                                                                                                                  erer.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/noninteractive_mode.o src/noninteractive_m                                                                                                                  ode.cpp
> g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/noninteractive_mode.o' src/noninteracti                                                                                                                  ve_mode.cpp > obj/noninteractive_mode.d
> g++ -c -std=c++11 -Wall -g -O0 -o obj/interactive_mode.o src/interactive_mode.cp                                                                                                                  p
> g++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See file:///usr/share/doc/gcc-4.9/README.Bugs for instructions.
> makefile:31: recipe for target 'obj/interactive_mode.o' failed
> make: **\* [obj/interactive_mode.o] Error 4
> emil@emil:~/comp-m2$

This time I also watched it happen through htop and in no part did I run out of memory.

**Comment by gto76** [comment]
Thanks for info,
I googled a little and mainly found that the trouble was not enough memory (or swap).
Can you post output of the `free -m` command... I tried to compile with 500MB of ram and 1500 of swap and it worked. Maybe try compiling in linux console (ctrl+alt+F1).

**Comment by emilfihlman** [comment]
Hi! I'm running this through ssh to my vps instance.

> emil@emil:~$ free -m
>             total       used       free     shared    buffers     cached
> Mem:           494        260        233         13         65         83
> -/+ buffers/cache:        111        383
> Swap:            0          0          0
> emil@emil:~$

Hmm, apparently my swap is not enabled. I shall attempt to enable it.

**Comment by emilfihlman** [comment]
So I took a stab at it:

emil@emil:~/comp-m2$ free -m
             total       used       free     shared    buffers     cached
Mem:           494        143        351          4         13         73
-/+ buffers/cache:         55        438
Swap:          999          0        999
emil@emil:~/comp-m2$ make clean
rm -f obj/\* comp
emil@emil:~/comp-m2$ make
g++ -c -std=c++11 -Wall -g -O0 -o obj/printer.o src/printer.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/printer.o' src/printer.cpp > obj/printer.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/cursor.o src/cursor.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/cursor.o' src/cursor.cpp > obj/cursor.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/specific_instruction.o src/specific_instruction.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/specific_instruction.o' src/specific_instruction.cpp > obj/specific_instruction.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/pipe_input.o src/pipe_input.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/pipe_input.o' src/pipe_input.cpp > obj/pipe_input.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/view.o src/view.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/view.o' src/view.cpp > obj/view.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/output.o src/output.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/output.o' src/output.cpp > obj/output.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/instruction.o src/instruction.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/instruction.o' src/instruction.cpp > obj/instruction.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/renderer.o src/renderer.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/renderer.o' src/renderer.cpp > obj/renderer.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/noninteractive_mode.o src/noninteractive_mode.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/noninteractive_mode.o' src/noninteractive_mode.cpp > obj/noninteractive_mode.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/interactive_mode.o src/interactive_mode.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/interactive_mode.o' src/interactive_mode.cpp > obj/interactive_mode.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/comp.o src/comp.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/comp.o' src/comp.cpp > obj/comp.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/load.o src/load.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/load.o' src/load.cpp > obj/load.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/parser.o src/parser.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/parser.o' src/parser.cpp > obj/parser.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/ram.o src/ram.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/ram.o' src/ram.cpp > obj/ram.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/cpu.o src/cpu.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/cpu.o' src/cpu.cpp > obj/cpu.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/address.o src/address.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/address.o' src/address.cpp > obj/address.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/standard_output.o src/standard_output.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/standard_output.o' src/standard_output.cpp > obj/standard_output.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/random_input.o src/random_input.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/random_input.o' src/random_input.cpp > obj/random_input.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/computer.o src/computer.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/computer.o' src/computer.cpp > obj/computer.d
g++ -c -std=c++11 -Wall -g -O0 -o obj/util.o src/util.cpp
g++ -MM -std=c++11 -Wall -g -O0 -MT 'obj/util.o' src/util.cpp > obj/util.d
gcc -c -std=gnu11 -Wall -g -O0 -o obj/environment.o src/environment.c
gcc -MM -std=gnu11 -Wall -g -O0 -MT 'obj/environment.o' src/environment.c > obj/environment.d
g++ -o comp obj/printer.o obj/cursor.o obj/specific_instruction.o obj/pipe_input.o obj/view.o obj/output.o obj/instruction.o obj/renderer.o obj/noninteractive_mode.o obj/interactive_mode.o obj/comp.o obj/load.o obj/parser.o obj/ram.o obj/cpu.o obj/address.o obj/standard_output.o obj/random_input.o obj/computer.o obj/util.o obj/environment.o
emil@emil:~/comp-m2$ ls
comp  doc  Dockerfile  examples  LICENSE  makefile  obj  README.md  run  src  tools
emil@emil:~/comp-m2$ ./run
Compiling... (may take some time)
./tools/parseDrawing drawing3D > /tmp/drawing.hpp
/bin/sh: 1: ./tools/parseDrawing: Permission denied
makefile:48: recipe for target 'src/drawing3D.hpp' failed
make: **\* [src/drawing3D.hpp] Error 126
emil@emil:~/comp-m2$

Now we have comp but ./run still produces errors.

**Comment by emilfihlman** [comment]
But ./comp seems to work based on make clean and make.

**Comment by gto76** [comment]
Well, run basically just runs `make` and then `./comp`.
Can you try `make clean` and then `run`.
If it still doesn't work, there's probably a problem with permissions/ownership of `run`, `tools/parseDrawing` or a `/tmp` folder.
You can inspect them by running `ls -l run tools/parseDrawing -d /tmp` in comp-m2's folder.
On my system they are:

```
-rwxrwx---  1 root vboxsf   189 Oct  4 02:50 run
drwxrwxrwt 13 root root   12288 Oct 17 18:20 /tmp
-rwxrwx---  1 root vboxsf   619 Sep 16 20:20 tools/parseDrawing

```

**Comment by emilfihlman** [comment]
It works so I suppose it's about memory issues though ¯\_(ツ)_/¯

**Comment by gto76** [comment]
Cool
